# Generated by Django 4.2.5 on 2024-01-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('companylogo', models.FileField(blank=True, null=True, upload_to='company/')),
            ],
        ),
        migrations.CreateModel(
            name='masterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pasword', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('candidatelogo', models.FileField(blank=True, null=True, upload_to='candidatelogo/')),
                ('mastermodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mastermodel')),
            ],
        ),
        migrations.CreateModel(
            name='postjobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=40, null=True)),
                ('jobdescription', models.TextField()),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.CharField(blank=True, max_length=20, null=True)),
                ('salarytype', models.CharField(blank=True, choices=[('month', 'month'), ('year', 'year')], max_length=30, null=True)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.companymodel')),
            ],
        ),
        migrations.AddField(
            model_name='companymodel',
            name='mastermodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mastermodel'),
        ),
    ]
