# Generated by Django 4.2.5 on 2024-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobmodel',
            name='companyimage',
            field=models.FileField(blank=True, null=True, upload_to='companyimage/'),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='companyname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
